//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stocktake_V4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siixsem_wip_config_dbEntities : DbContext
    {
        public siixsem_wip_config_dbEntities()
            : base("name=siixsem_wip_config_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<getSemiFGByModel_Result> getSemiFGByModel(string model)
        {
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSemiFGByModel_Result>("getSemiFGByModel", modelParameter);
        }
    
        public virtual ObjectResult<getSemiManuByModel_Result> getSemiManuByModel(string model)
        {
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSemiManuByModel_Result>("getSemiManuByModel", modelParameter);
        }
    
        public virtual ObjectResult<getSemiSMTByModel_Result> getSemiSMTByModel(string model)
        {
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSemiSMTByModel_Result>("getSemiSMTByModel", modelParameter);
        }
    
        public virtual ObjectResult<getSemiSMTTByModel_Result> getSemiSMTTByModel(string model)
        {
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSemiSMTTByModel_Result>("getSemiSMTTByModel", modelParameter);
        }
    }
}
